/*
 * HubForm.java
 *
 * Created on March 1, 2007, 3:42 PM
 */

package net.lizhao.datahub.gui;

import java.util.*;
import net.lizhao.datahub.core.control.*;
/**
 *
 * @author  zhaoli
 */
public class HubForm extends javax.swing.JFrame {
    private ResourceBundle strTable;

    /** Creates new form HubForm */
    public HubForm() {
        strTable = ResourceBundle.getBundle(this.getClass().getPackage().getName()+".lang.StringTableInt");
        initComponents();
        init();
    }
    
    private CmdMenuItem MenuHelpAbout;
    private void init()
    {
    	MenuHelpAbout = new CmdMenuItem();
    	MenuHelpAbout.setCommandItem(new HelpCommand());
    	MenuHelpAbout.setText("About DataHub");
    	HelpMenu.add(MenuHelpAbout);
    	MenuHelpAbout.addActionListener(MenuHelpAbout.getCommandItem());
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        MainMenu = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        MenuNewEntry = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        ViewMenu = new javax.swing.JMenu();
        MenuSideBar = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        ToolsMenu = new javax.swing.JMenu();
        WindowsMenu = new javax.swing.JMenu();
        HelpMenu = new javax.swing.JMenu();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jToolBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar1.setFloatable(false);
        jButton1.setText("jButton1");
        jToolBar1.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jToolBar1, gridBagConstraints);

        jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar2.setFloatable(false);
        jButton2.setText("jButton2");
        jToolBar2.add(jButton2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jToolBar2, gridBagConstraints);

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setDividerSize(7);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane2.setDividerLocation(100);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane2.setOneTouchExpandable(true);
        jScrollPane1.setViewportView(jTree1);

        jSplitPane2.setTopComponent(jScrollPane1);

        jSplitPane1.setLeftComponent(jSplitPane2);

        jSplitPane1.setRightComponent(jTabbedPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jSplitPane1, gridBagConstraints);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 20));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 20));
        jLabel1.setText("jLabel1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);

        jPanel1.add(jSeparator2);

        jLabel2.setText("jLabel2");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2);

        jPanel1.add(jSeparator3);

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        FileMenu.setText(strTable.getString("MenuFile"));
        MenuNewEntry.setText(strTable.getString("MenuNewEntry"));
        MenuNewEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuNewEntryActionPerformed(evt);
            }
        });
        MenuNewEntry.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ff(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        FileMenu.add(MenuNewEntry);

        MainMenu.add(FileMenu);

        EditMenu.setText(strTable.getString("MenuEdit"));
        MainMenu.add(EditMenu);

        ViewMenu.setText(strTable.getString("MenuView"));
        MenuSideBar.setText(strTable.getString("MenuSideBar"));
        MenuSideBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSideBarActionPerformed(evt);
            }
        });

        ViewMenu.add(MenuSideBar);

        ViewMenu.add(jSeparator1);

        jMenu1.setText("Menu");
        jCheckBoxMenuItem1.setText("CheckBox");
        jMenu1.add(jCheckBoxMenuItem1);

        ViewMenu.add(jMenu1);

        MainMenu.add(ViewMenu);

        ToolsMenu.setText(strTable.getString("MenuTools"));
        MainMenu.add(ToolsMenu);

        WindowsMenu.setText(strTable.getString("MenuWindows"));
        MainMenu.add(WindowsMenu);

        HelpMenu.setText(strTable.getString("MenuHelp"));
        MainMenu.add(HelpMenu);

        setJMenuBar(MainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ff(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ff
// TODO add your handling code here:
    }//GEN-LAST:event_ff

    private void MenuSideBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSideBarActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_MenuSideBarActionPerformed

    private void MenuNewEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuNewEntryActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_MenuNewEntryActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HubForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JMenuItem MenuNewEntry;
    private javax.swing.JCheckBoxMenuItem MenuSideBar;
    private javax.swing.JMenu ToolsMenu;
    private javax.swing.JMenu ViewMenu;
    private javax.swing.JMenu WindowsMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
    
}
